alias opv='open /Volumes/'
alias gsk='cat ~/.ssh/id_rsa.pub'
alias rstudio='open -a Rstudio'
alias topi='ssh nanjow@192.168.1.2'
alias cls='clear; ls'
alias clr='clear; ls -a;'
alias cla='clear; ls -la;'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias ~='cd ~'
alias mf='cd ~/MediaFire'
alias cb='cat ~/.bash_aliases'
alias ca='cd ~/MediaFire/Akiba-Trip'
alias rrr='cd ~/MediaFire/School/Spring2016/R'
alias 567='cd ~/MediaFire/School/Spring2016/CSCI567/CSCI567-Wesley-Nanjo'
alias sp='cd ~/MediaFire/School/Spring2016/SeniorProject'
alias sch='cd ~/MediaFire/School/'
alias eb='vim ~/.bash_aliases'
alias sb='source ~/.bash_aliases'
alias rr='cd ~/MediaFire/WebFinal'
alias dl='cd ~/Downloads'
alias dk='cd ~/Desktop'
alias fc='ls | wc -l'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias mkpdir='mkdir -pv'
alias ports='netstat -tulanp'
alias playavi='mplayer *.avi'
alias vlc='vlc *.avi'
alias playwave='for i in *.wav; do mplayer "$i"; done'
alias playogg='for i in *.ogg; do mplayer "$i"; done'
alias playmp3='for i in *.mp3; do mplayer "$i"; done'
alias sss='sudo shutdown -r now'
